name: Basic github action test

on: [push]

jobs:
  simpeHelloWorldJob:
    runs-on: ubuntu:20.04
    steps:
      - name: "command name goes here"
      - run: | 
            echo 'hello from gitlba runner'
