name: Basic github action test

on: [push]

jobs:
  simpeHelloWorldJob:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "command name goes here"
        run: | 
          echo 'starting'
      - name: "env setup"
        run: |
          pip install -r deps/req.txt

      - name: "unit test 1"
        run: |
          python tests/env.test.py
