name: Basic github action test

on: [push]

jobs:
  simpeHelloWorldJob:
    runs-on: ubuntu-20.04

    env:
      TEST_SECRET: ${{ secrets.test }}
    steps:
      - uses: actions/checkout@v3
      - name: "preload config"
        run: | 
          echo 'starting' \ &&
          echo 'your secret: '$TEST_SECRET
      - name: "env setup"
        run: |
          pip install -r deps/req.txt

      - name: "unit test 1"
        run: |
          python tests/env.test.py
